### ISSUE TITLE
News Section Makers Innovation Award - translation to UA 

### ISSUE THREAD

**Issue by Jacky-Bertlich** [tolocar-project/website#108]
Is it possible to change the EN description for the Maker Innovation Award tile to UA? (of course not the rest of News section as it is linked with Airtable). 

EN: Where Networking Meets Funding, Mentoring Sparks Ideas, and Innovation Comes to Life!
UA: тут нетворкінг зустрічається з фінансуванням, менторство запалює ідеї, а інновації втілюються в життя!

News = Новини  

Find all news on = Слідкуйте за нами

**Comment by pReya** [comment]
I would love to combine this with the general translation of the individual news section content. But I don't know the state of the AirTable content. Do we have UA content for all/most of the content items?

**Comment by Jacky-Bertlich** [comment]
Sure, that makes sense. We just added another column in Airtable. You can use this now for the UA titles (Name UA) for the automatization: https://airtable.com/appy8mE1ZpLXfYzEQ/tblvfXTgnme0tqIQD/viwPFvGErTUypvvuE/fldZmTlKyR1bTqkIL
