### ISSUE TITLE
Update Navi Bar 

### ISSUE THREAD

**Issue by Jacky-Bertlich** [tolocar-project/website#142]
Could you delete the "What is a Tolocar?" in the navi bar at the top of website for both EN and UA website? This is redundant and otherwise its getting crowded at the top. You can leave "What is a tolocar" at the bottom of the website :)

In UA: [Що таке толокар?](https://tolocar.org/ua/#what-is-a-tolocar)

![image](https://github.com/tolocar-project/website/assets/132373047/6c99bc48-02a3-44bf-99e9-c564604bc511)

**Comment by pReya** [comment]
done
