### ISSUE TITLE
UI/CSS Framework or not?

### ISSUE THREAD

**Issue by pReya** [tolocar-project/website#2]
One thing we did not talk about in the Kickoff meeting is the topic of UI/CSS frameworks. Do we want to use any framework for utility classes in CSS (e.g. colors, spacing, radiuses, etc.) or do we "start from scratch"? Any preferences on your side @tobimori? I'm fine either way, but I suppose we could move a little faster using something like TailwindCSS.

**Comment by tobimori** [comment]
I'm fine either way, although I prefer classic (S)CSS or styled-components syntax usually. I'd also suggest [xstyled](https://xstyled.dev/) - it's like Tailwind meets styled-components in React.

In the end, you'll be doing most of the legwork regarding development, so I'd leave that choice to you.

**Comment by pReya** [comment]
I was talking more about the visual side of it, that's why I asked you explicitly. Are you going to/do you want to use any existing set of defaults for spacing, radiuses, shadows, breakpoint sizes, font sizes, line spacing, etc. Tailwind offers a set of default values that typically works very well. I was suggesting it might save some time to use these "scales" instead of defining everything from scratch.

**Comment by tobimori** [comment]
I'd not use defaults usually, e.g. I'm not really happy with Tailwinds default color palette as it's too bluish usually, but instead define my own. Although I yet can't really say anything about how the design will end.

**Comment by pReya** [comment]
Alright, that's what I wanted to know. Thanks for sharing your approach!
