### ISSUE TITLE
Reduced navigation margins only when scrolling

### ISSUE THREAD

**Issue by tobimori** [tolocar-project/website#50]
<img width="1512" alt="CleanShot 2022-10-31 at 16 38 06@2x" src="https://user-images.githubusercontent.com/29142128/199048072-f8050fc5-3548-458b-93d0-94a6a24487ad.png">

<img width="685" alt="CleanShot 2022-10-31 at 16 38 24@2x" src="https://user-images.githubusercontent.com/29142128/199048094-ce3dd7ce-894b-48bb-90a0-2f30a207ecad.png">

See design

**Comment by pReya** [comment]
This should be fixed now. Can you confirm @tobimori?

**Comment by tobimori** [comment]
<img width="490" alt="CleanShot 2023-02-02 at 12 38 09@2x" src="https://user-images.githubusercontent.com/29142128/216314884-e660dd74-15f6-46dc-9185-6d8a55ca8914.png">
Nav background color should always be full white on scroll, no matter the header color.
It should be transparent when not scrolled yet (-> header color).

**Comment by tobimori** [comment]
Another bug with the background on the legal page: https://tolocar.org/en/legal/
